### ISSUE TITLE
Bump "Tested up to" for WooCommerce 4.1

### ISSUE THREAD

**Issue by stevegrunwell** [nexcess/limit-orders#28]
Now that WooCommerce 4.1 is available, ensure we're compatible (which, based on our CI/CD pipeline, we are).

![WooCommerce 4.1 upgrade notice, noting that Limit Orders is only tested up to 4.0](https://user-images.githubusercontent.com/233836/81110025-f7d96d80-8ee8-11ea-8383-55b561729980.png)

**Comment by bswatson** [comment]
Closed with #29
